version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      prod-deps:
        dependency-type: 'production'
      dev-deps:
        dependency-type: 'development'
    ignore:
      - dependency-name: '@types/react*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
      - dependency-name: '@eslint/*'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'eslint*'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'globals'
        update-types:
          - 'version-update:semver-major'
    commit-message:
      prefix: 'build'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      actions:
        patterns:
          - '*'
    commit-message:
      prefix: 'ci'
      include: 'scope'
